CREATE TABLE public.security_products (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL DEFAULT 'kamera',
  variation TEXT,
  brand TEXT,
  model TEXT,
  specs TEXT,
  price NUMERIC NOT NULL DEFAULT 0,
  currency TEXT NOT NULL DEFAULT 'TRY',
  stock INTEGER NOT NULL DEFAULT 0,
  supplier TEXT,
  notes TEXT,
  sort_order INTEGER NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.security_products TO anon, authenticated;
GRANT ALL ON public.security_products TO service_role;

ALTER TABLE public.security_products ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all access to security_products" ON public.security_products FOR ALL USING (true) WITH CHECK (true);

CREATE TRIGGER update_security_products_updated_at BEFORE UPDATE ON public.security_products FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- Seed common CCTV materials (prices left at 0 for user to fill in)
INSERT INTO public.security_products (name, category, variation, brand, sort_order) VALUES
('2MP Bullet Kamera', 'kamera', 'AHD', 'Hikvision', 10),
('2MP Dome Kamera', 'kamera', 'AHD', 'Hikvision', 11),
('5MP Bullet Kamera', 'kamera', 'AHD', 'Hikvision', 12),
('5MP Dome Kamera', 'kamera', 'AHD', 'Hikvision', 13),
('2MP Bullet Kamera', 'kamera', 'AHD', 'Dahua', 20),
('2MP Dome Kamera', 'kamera', 'AHD', 'Dahua', 21),
('5MP Bullet Kamera', 'kamera', 'AHD', 'Dahua', 22),
('5MP Dome Kamera', 'kamera', 'AHD', 'Dahua', 23),
('2MP Bullet Kamera', 'kamera', 'AHD', 'OEM', 30),
('2MP Dome Kamera', 'kamera', 'AHD', 'OEM', 31),
('5MP Bullet Kamera', 'kamera', 'AHD', 'OEM', 32),
('4MP IP Bullet Kamera PoE', 'kamera', 'IP', 'Hikvision', 40),
('4MP IP Dome Kamera PoE', 'kamera', 'IP', 'Hikvision', 41),
('8MP IP Bullet Kamera PoE', 'kamera', 'IP', 'Hikvision', 42),
('4MP IP Bullet Kamera PoE', 'kamera', 'IP', 'Dahua', 50),
('4MP IP Dome Kamera PoE', 'kamera', 'IP', 'Dahua', 51),
('8MP IP Bullet Kamera PoE', 'kamera', 'IP', 'Dahua', 52),
('4MP IP Bullet Kamera PoE', 'kamera', 'IP', 'OEM', 60),
('4MP IP Dome Kamera PoE', 'kamera', 'IP', 'OEM', 61),
('4 Kanal DVR', 'dvr', 'AHD', 'Hikvision', 100),
('8 Kanal DVR', 'dvr', 'AHD', 'Hikvision', 101),
('16 Kanal DVR', 'dvr', 'AHD', 'Hikvision', 102),
('4 Kanal DVR', 'dvr', 'AHD', 'Dahua', 110),
('8 Kanal DVR', 'dvr', 'AHD', 'Dahua', 111),
('16 Kanal DVR', 'dvr', 'AHD', 'Dahua', 112),
('4 Kanal DVR', 'dvr', 'AHD', 'OEM', 120),
('8 Kanal DVR', 'dvr', 'AHD', 'OEM', 121),
('4 Kanal NVR PoE', 'nvr', 'IP', 'Hikvision', 130),
('8 Kanal NVR PoE', 'nvr', 'IP', 'Hikvision', 131),
('16 Kanal NVR PoE', 'nvr', 'IP', 'Hikvision', 132),
('4 Kanal NVR PoE', 'nvr', 'IP', 'Dahua', 140),
('8 Kanal NVR PoE', 'nvr', 'IP', 'Dahua', 141),
('16 Kanal NVR PoE', 'nvr', 'IP', 'Dahua', 142),
('4 Kanal NVR PoE', 'nvr', 'IP', 'OEM', 150),
('8 Kanal NVR PoE', 'nvr', 'IP', 'OEM', 151),
('1TB Güvenlik HDD (Purple)', 'hdd', NULL, 'WD', 200),
('2TB Güvenlik HDD (Purple)', 'hdd', NULL, 'WD', 201),
('4TB Güvenlik HDD (Purple)', 'hdd', NULL, 'WD', 202),
('1TB Güvenlik HDD (SkyHawk)', 'hdd', NULL, 'Seagate', 210),
('2TB Güvenlik HDD (SkyHawk)', 'hdd', NULL, 'Seagate', 211),
('4TB Güvenlik HDD (SkyHawk)', 'hdd', NULL, 'Seagate', 212),
('BNC Konnektör (Vidalı)', 'konnektor', 'AHD', NULL, 300),
('BNC Konnektör (Sıkıştırmalı)', 'konnektor', 'AHD', NULL, 301),
('DC Power Jack', 'konnektor', NULL, NULL, 302),
('RJ45 Konnektör (CAT6)', 'konnektor', 'IP', NULL, 303),
('RJ45 Konnektör (CAT5e)', 'konnektor', 'IP', NULL, 304),
('BNC + DC Combo Konnektör', 'konnektor', 'AHD', NULL, 305),
('2+1 Kamera Kablosu (metre)', 'kablo', 'AHD', NULL, 400),
('4+1 Kamera Kablosu (metre)', 'kablo', 'AHD', NULL, 401),
('RG59 Coaxial Kablo (metre)', 'kablo', 'AHD', NULL, 402),
('CAT6 UTP Kablo (metre)', 'kablo', 'IP', NULL, 403),
('CAT6 FTP Kablo (metre)', 'kablo', 'IP', NULL, 404),
('CAT5e UTP Kablo (metre)', 'kablo', 'IP', NULL, 405),
('12V 2A Adaptör', 'adaptor', NULL, NULL, 500),
('12V 5A Adaptör', 'adaptor', NULL, NULL, 501),
('12V 10A Adaptör (Merkezi)', 'adaptor', NULL, NULL, 502),
('4 Kanal Power Splitter', 'adaptor', NULL, NULL, 503),
('8 Kanal Power Splitter', 'adaptor', NULL, NULL, 504),
('4 Port PoE Switch', 'switch', 'IP', NULL, 600),
('8 Port PoE Switch', 'switch', 'IP', NULL, 601),
('16 Port PoE Switch', 'switch', 'IP', NULL, 602),
('24 Port PoE Switch', 'switch', 'IP', NULL, 603),
('HDMI Kablo 1.5m', 'kablo', NULL, NULL, 700),
('HDMI Kablo 3m', 'kablo', NULL, NULL, 701),
('HDMI Kablo 5m', 'kablo', NULL, NULL, 702),
('19'' LCD Monitör', 'monitor', NULL, NULL, 800),
('22'' LCD Monitör', 'monitor', NULL, NULL, 801),
('24'' LCD Monitör', 'monitor', NULL, NULL, 802),
('Metal Kamera Ayağı (Duvar)', 'aksesuar', NULL, NULL, 900),
('Metal Kamera Ayağı (Tavan)', 'aksesuar', NULL, NULL, 901),
('Plastik Buat', 'aksesuar', NULL, NULL, 902),
('Kablo Kanalı 25x16 (metre)', 'aksesuar', NULL, NULL, 903),
('Kablo Kanalı 40x25 (metre)', 'aksesuar', NULL, NULL, 904),
('Kablo Klipsi (paket)', 'aksesuar', NULL, NULL, 905),
('UPS (Kesintisiz Güç Kaynağı)', 'aksesuar', NULL, NULL, 906),
('Video Balun (çift)', 'aksesuar', 'AHD', NULL, 910),
('BNC Kablo (Hazır 20m)', 'kablo', 'AHD', NULL, 950),
('BNC Kablo (Hazır 30m)', 'kablo', 'AHD', NULL, 951);
